"""CLI app for running ConvertModelForMetaQuest as a remote worker."""

from __future__ import annotations

import argparse
import os
import platform
import threading
import uuid
from pathlib import Path

from .logging_utils import configure_logging
from .remote_client import RemoteWorkerClient
from .version import read_version
from .worker_loop import LoopConfig, NullWorkerObserver, WorkerLoop
from .worker_processor import PipelineOptions, PipelineProcessor

DEFAULT_HTTP_TIMEOUT_SECONDS = 60
DEFAULT_DOWNLOAD_TIMEOUT_SECONDS = 180
DEFAULT_UPLOAD_TIMEOUT_SECONDS = 600
DEFAULT_POLL_WAIT_SECONDS = 30
DEFAULT_RECONNECT_AFTER_FAILURES = 3


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run ConvertModelForMetaQuest as remote worker")
    parser.add_argument("--server-url", default=os.getenv("SERVER_URL"), help="HTTPS URL of Medical 3D Models API")
    parser.add_argument("--token", default=os.getenv("WORKER_TOKEN"), help="Worker auth token")
    parser.add_argument(
        "--worker-id",
        default=None,
        help="DEPRECATED fallback override for worker identifier (auto-generated by default)",
    )
    parser.add_argument(
        "--worker-name",
        default=None,
        help="DEPRECATED fallback override for worker name (auto-generated by default)",
    )

    gui_group = parser.add_mutually_exclusive_group()
    gui_group.add_argument("--with-gui", "--gui", dest="with_gui", action="store_true", help="Run with small GUI status window")
    gui_group.add_argument("--no-gui", action="store_true", help="Run headless (console logs only)")

    parser.add_argument("--work-dir", default="worker_runtime", help="Directory for downloaded/processed files")
    parser.add_argument(
        "--allow-insecure-http",
        action="store_true",
        help="Allow http:// server URL (for local development only)",
    )
    parser.add_argument(
        "--poll-wait",
        "--claim-wait",
        dest="poll_wait",
        type=int,
        default=None,
        help="DEPRECATED fallback for long-poll wait seconds (server runtime config preferred)",
    )
    parser.add_argument(
        "--heartbeat-interval",
        type=int,
        default=None,
        help="DEPRECATED fallback register hint for heartbeat interval",
    )
    parser.add_argument(
        "--lease-timeout",
        type=int,
        default=None,
        help="DEPRECATED fallback register hint for lease timeout",
    )
    parser.add_argument(
        "--max-download-bytes",
        type=int,
        default=1024 * 1024 * 1024,
        help="Maximum allowed downloaded input size in bytes",
    )
    parser.add_argument(
        "--http-timeout-seconds",
        type=int,
        default=None,
        help="DEPRECATED fallback HTTP timeout for API calls (server runtime config preferred)",
    )
    parser.add_argument(
        "--download-timeout-seconds",
        type=int,
        default=None,
        help="DEPRECATED fallback timeout for model download requests",
    )
    parser.add_argument(
        "--upload-timeout-seconds",
        type=int,
        default=None,
        help="DEPRECATED fallback timeout for result upload requests",
    )
    parser.add_argument(
        "--reconnect-after-failures",
        type=int,
        default=None,
        help="DEPRECATED fallback reconnect threshold (server runtime config preferred)",
    )
    parser.add_argument("--once", action="store_true", help="Run single claim cycle and exit")
    parser.add_argument("--dry-run", action="store_true", help="Validate config and exit without network calls")

    parser.add_argument("--blender-exec", help="Optional Blender executable path")
    parser.add_argument("--face-limit", type=int, default=400000)
    parser.add_argument("--blender-timeout-seconds", type=int, default=1800)
    parser.add_argument("--log-level", default="INFO")
    parser.add_argument("--version", action="store_true", help="Print worker version and exit")
    return parser


def _auto_worker_name() -> str:
    hostname = (platform.node() or "").strip()
    return hostname or "cmq-worker"


def _slugify_hostname(name: str) -> str:
    normalized = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "-" for ch in name.strip())
    collapsed = "-".join(part for part in normalized.split("-") if part)
    return collapsed.lower() or "cmq-worker"


def _auto_worker_id(worker_name: str) -> str:
    short_uuid = uuid.uuid4().hex[:8]
    return f"worker-{_slugify_hostname(worker_name)}-{short_uuid}"


def _resolve_gui_mode(args: argparse.Namespace) -> bool:
    if args.with_gui:
        return True
    if args.no_gui:
        return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.version:
        print(read_version())
        return 0

    logger = configure_logging(args.log_level)

    env_worker_name = os.getenv("WORKER_NAME")
    env_worker_id = os.getenv("WORKER_ID")
    resolved_worker_name = (args.worker_name or env_worker_name or _auto_worker_name()).strip() or "cmq-worker"
    resolved_worker_id = (args.worker_id or env_worker_id or _auto_worker_id(resolved_worker_name)).strip()
    if not resolved_worker_id:
        resolved_worker_id = _auto_worker_id(resolved_worker_name)

    deprecated_flag_values = {
        "--worker-id": args.worker_id,
        "--worker-name": args.worker_name,
        "--heartbeat-interval": args.heartbeat_interval,
        "--lease-timeout": args.lease_timeout,
        "--http-timeout-seconds": args.http_timeout_seconds,
        "--download-timeout-seconds": args.download_timeout_seconds,
        "--upload-timeout-seconds": args.upload_timeout_seconds,
        "--reconnect-after-failures": args.reconnect_after_failures,
    }
    deprecated_used = [flag for flag, value in deprecated_flag_values.items() if value is not None]
    if deprecated_used:
        logger.warning(
            "Deprecated worker options provided (%s). Server runtime config should control these values.",
            ", ".join(deprecated_used),
        )

    if args.dry_run:
        logger.info(
            "Dry run complete. version=%s worker_name=%s worker_id=%s",
            read_version(),
            resolved_worker_name,
            resolved_worker_id,
        )
        return 0

    if not args.server_url:
        logger.error("Missing --server-url or SERVER_URL")
        return 2
    if not args.token:
        logger.error("Missing --token or WORKER_TOKEN")
        return 2

    use_gui = _resolve_gui_mode(args)

    try:
        client = RemoteWorkerClient(
            server_url=args.server_url,
            worker_token=args.token,
            worker_name=resolved_worker_name,
            worker_id=resolved_worker_id,
            timeout=max(10, int(args.http_timeout_seconds or DEFAULT_HTTP_TIMEOUT_SECONDS)),
            download_timeout=max(10, int(args.download_timeout_seconds or DEFAULT_DOWNLOAD_TIMEOUT_SECONDS)),
            upload_timeout=max(10, int(args.upload_timeout_seconds or DEFAULT_UPLOAD_TIMEOUT_SECONDS)),
            allow_insecure_http=bool(args.allow_insecure_http),
            heartbeat_interval_hint=args.heartbeat_interval,
            lease_timeout_hint=args.lease_timeout,
        )
    except ValueError as exc:
        logger.error("Invalid worker configuration: %s", exc)
        return 1

    processor = PipelineProcessor(
        blender_exec=args.blender_exec,
        options=PipelineOptions(
            face_limit=args.face_limit,
            blender_timeout_seconds=args.blender_timeout_seconds,
        ),
    )

    loop = WorkerLoop(
        client=client,
        processor=processor,
        work_root=Path(args.work_dir).expanduser().resolve(),
        logger=logger,
        observer=NullWorkerObserver(),
        config=LoopConfig(
            poll_wait_seconds=max(1, int(args.poll_wait or DEFAULT_POLL_WAIT_SECONDS)),
            once=args.once,
            max_download_bytes=args.max_download_bytes,
            reconnect_after_failures=max(
                1, int(args.reconnect_after_failures or DEFAULT_RECONNECT_AFTER_FAILURES)
            ),
        ),
    )

    if not use_gui:
        return loop.run_forever()

    try:
        from .gui_log_window import GuiLogWindow
    except Exception as exc:
        logger.warning("GUI import unavailable: %s. Falling back to --no-gui.", exc)
        return loop.run_forever()

    try:
        gui = GuiLogWindow(app_version=read_version())
        gui.attach_logger(logger)
        gui.bind_stop_event(loop.stop_event)
        loop.observer = gui
    except Exception as exc:
        logger.warning("GUI initialization failed: %s. Falling back to --no-gui.", exc)
        return loop.run_forever()

    result = {"code": 0}

    def _worker_thread() -> None:
        result["code"] = loop.run_forever()

    thread = threading.Thread(target=_worker_thread, daemon=True)
    thread.start()
    try:
        gui.run()
    finally:
        loop.stop()
        thread.join(timeout=5)

    return int(result["code"])


if __name__ == "__main__":
    raise SystemExit(main())
